sudo : required
services:
  - docker

before_install:
  - docker build -t NiniiGit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run NiniiGit/react-test npm test -- --coverage

after_success:
  - docker build -t NiniiGit/multi-client ./client
  - docker build -t NiniiGit/multi-nginx ./nginx
  - docker build -t NiniiGit/multi-server ./server
  - docker build -t NiniiGit/multi-worker ./worker


  #docker login to dockercli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  #take thos images and push on h
  - docker push NiniiGit/multi-client
  - docker push NiniiGit/multi-nginx
  - docker push NiniiGit/multi-server
  - docker push NiniiGit/multi-worker
  
