sudo : required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t ninadocker73/multi-client ./client
  - docker build -t ninadocker73/multi-nginx ./nginx
  - docker build -t ninadocker73/multi-server ./server
  - docker build -t ninadocker73/multi-worker ./worker


  #docker login to dockercli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  #take thos images and push on h
  - docker push ninadocker73/multi-client
  - docker push ninadocker73/multi-nginx
  - docker push ninadocker73/multi-server
  - docker push ninadocker73/multi-worker
  
