sudo : required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t ninadocker73/multi-client ./client
  - docker build -t ninadocker73/multi-nginx ./nginx
  - docker build -t ninadocker73/multi-server ./server
  - docker build -t ninadocker73/multi-worker ./worker


  #docker login to dockercli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  #take thos images and push on h
  - docker push ninadocker73/multi-client
  - docker push ninadocker73/multi-nginx
  - docker push ninadocker73/multi-server
  - docker push ninadocker73/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker  
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-048831836751
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  
